#!/bin/bash

RELATIVE_PATH="$(dirname $0)/../../"
ROOT_PATH="$(readlink -f $RELATIVE_PATH)"

PIDFILE="${ROOT_PATH}/django-flup.pid"
SOCKETFILE="${ROOT_PATH}/django.sock"
OUTLOG="${ROOT_PATH}/django.out"
ERRLOG="${ROOT_PATH}/django.err"

sudo service nginx stop
kill `cat $PIDFILE`
find . -iname '*.pyc' -exec rm {} \;
git fetch
git pull --ff-only -v
sudo pip install -r pip-requirements
./manage.py syncdb
./manage.py migrate
echo "yes" | ./manage.py collectstatic
sg velocity_achievements_web "./manage.py runfcgi socket=$SOCKETFILE pidfile=$PIDFILE umask=0002 debug=True outlog=$OUTLOG errlog=$ERRLOG"
sudo service nginx start
